/**
 * Local execution for the pandas variant of LeetCode database problems.
 *
 * Solving in pandas shares nothing with solving in SQL except the data: the
 * problem hands you a function taking one DataFrame per table instead of a query.
 * So this runner writes a harness that seeds those DataFrames from the same
 * `{headers, rows}` example dataset the SQL path uses, imports the user's file,
 * calls the entry function, and prints the result as a JSON grid.
 *
 * Seeding deliberately ignores the API's `dataSchemas` pandas snippets: on some
 * problems their column order disagrees with the SQL example data, which would
 * make the two modes disagree about what the input even is.
 */
import * as fs from "fs/promises";
import * as os from "os";
import * as path from "path";
import { runSandboxed } from "../Sandbox";
import type { DbGrid, DbSchema, DbSeedTable } from "./DbProblem";

const RESULT_SENTINEL = "__LCEX_PANDAS_RESULT__";
const RUN_TIMEOUT_MS = 20_000;

function quoteShellPath(p: string): string {
  return p.includes(" ") ? `"${p.replace(/"/g, '\\"')}"` : p;
}

/** pandas dtype for a MySQL column type. */
function pandasDtype(mysqlType: string): string {
  const t = mysqlType.trim().toUpperCase();
  if (/^(TINYINT|SMALLINT|MEDIUMINT|INT|INTEGER|BIGINT|BIT)/.test(t)) return "Int64";
  if (/^BOOL/.test(t)) return "boolean";
  if (/^(DECIMAL|NUMERIC|FLOAT|DOUBLE|REAL)/.test(t)) return "float64";
  if (/^(DATE|DATETIME|TIMESTAMP)/.test(t)) return "datetime64[ns]";
  return "object";
}

export interface PandasRunPlan {
  /** Table name -> ordered column list, matching the seed row tuples. */
  tables: Array<{ name: string; columns: string[]; rows: unknown[][]; dtypes: Record<string, string> }>;
  functionName: string;
}

export function buildRunPlan(schema: DbSchema, seed: readonly DbSeedTable[]): PandasRunPlan {
  const typeFor = new Map<string, Map<string, string>>();
  for (const t of schema.tables) {
    typeFor.set(
      t.name.toLowerCase(),
      new Map(t.columns.map((c) => [c.name.toLowerCase(), c.type]))
    );
  }
  return {
    functionName: schema.functionName,
    tables: seed.map((t) => {
      const columnTypes = typeFor.get(t.name.toLowerCase());
      const dtypes: Record<string, string> = {};
      for (const col of t.columns) {
        const declared = columnTypes?.get(col.toLowerCase());
        dtypes[col] = pandasDtype(declared ?? "VARCHAR");
      }
      return { name: t.name, columns: t.columns, rows: t.rows, dtypes };
    }),
  };
}

/**
 * The harness. Kept as a single Python file so the only runtime requirement is
 * `python3` plus pandas; nothing is installed and nothing is imported from the
 * extension's own tree.
 */
function buildHarness(solutionPath: string, plan: PandasRunPlan): string {
  // Base64 rather than an inline literal: the plan holds arbitrary problem data,
  // and no quoting style survives every string a table cell might contain.
  const planB64 = Buffer.from(JSON.stringify(plan), "utf8").toString("base64");
  return `# Generated by lcex. Seeds the problem's tables, calls your function, prints the result.
import base64
import datetime
import importlib.util
import inspect
import json
import math

import pandas as pd

PLAN = json.loads(base64.b64decode("${planB64}").decode("utf-8"))
SOLUTION_PATH = ${JSON.stringify(solutionPath)}
SENTINEL = ${JSON.stringify(RESULT_SENTINEL)}


def build_frames():
    frames = {}
    for table in PLAN["tables"]:
        frame = pd.DataFrame(table["rows"], columns=table["columns"])
        for column, dtype in table["dtypes"].items():
            if column not in frame.columns:
                continue
            try:
                if dtype.startswith("datetime64"):
                    frame[column] = pd.to_datetime(frame[column], errors="coerce")
                else:
                    frame[column] = frame[column].astype(dtype)
            except (TypeError, ValueError):
                # Leave the column as-is rather than failing the whole run.
                pass
        frames[table["name"]] = frame
    return frames


def load_solution():
    spec = importlib.util.spec_from_file_location("lcex_solution", SOLUTION_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError("could not load the solution file")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def pick_entry(module):
    """PLAN's name first; otherwise the only DataFrame-taking function defined here."""
    named = getattr(module, PLAN["functionName"], None)
    if callable(named):
        return named
    candidates = [
        value
        for name, value in vars(module).items()
        if inspect.isfunction(value)
        and value.__module__ == module.__name__
        and not name.startswith("_")
    ]
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise RuntimeError(
            "no function found in this file (expected one named %r)" % PLAN["functionName"]
        )
    raise RuntimeError(
        "several functions defined here; name the entry point %r so lcex knows which to call"
        % PLAN["functionName"]
    )


def bind_arguments(entry, frames):
    """Match parameters to tables by name, falling back to declaration order."""
    params = list(inspect.signature(entry).parameters.values())
    by_lower = {name.lower(): frame for name, frame in frames.items()}
    ordered = list(frames.values())
    args = []
    for index, param in enumerate(params):
        key = param.name.lower()
        if key in by_lower:
            args.append(by_lower[key])
        elif index < len(ordered):
            args.append(ordered[index])
        else:
            raise RuntimeError("parameter %r does not match any table" % param.name)
    return args


def cell(value):
    if value is None or value is pd.NaT:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(value, (pd.Timestamp, datetime.datetime, datetime.date)):
        as_ts = pd.Timestamp(value)
        if as_ts.hour or as_ts.minute or as_ts.second:
            return as_ts.strftime("%Y-%m-%d %H:%M:%S")
        return as_ts.strftime("%Y-%m-%d")
    if hasattr(value, "item"):
        try:
            value = value.item()
        except (AttributeError, ValueError):
            pass
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, (int, float, str)):
        return value
    return str(value)


def to_grid(result):
    if isinstance(result, pd.Series):
        result = result.to_frame()
    if not isinstance(result, pd.DataFrame):
        raise RuntimeError(
            "the function returned %s; LeetCode expects a pandas DataFrame"
            % type(result).__name__
        )
    columns = [str(c) for c in result.columns]
    rows = [[cell(v) for v in row] for row in result.itertuples(index=False, name=None)]
    return {"columns": columns, "rows": rows}


def main():
    frames = build_frames()
    entry = pick_entry(load_solution())
    result = entry(*bind_arguments(entry, frames))
    print(SENTINEL + json.dumps(to_grid(result)))


main()
`;
}

export interface PandasRunResult {
  grid: DbGrid;
  /** Anything the solution printed itself, with the result line removed. */
  stdout: string;
}

/** Raised when python3 or pandas is unavailable, so callers can show install guidance. */
export class PandasUnavailableError extends Error {}

export async function isPandasAvailable(): Promise<boolean> {
  const { exitCode } = await runSandboxed('python3 -c "import pandas"', {
    cwd: os.tmpdir(),
    timeout: 15_000,
  });
  return exitCode === 0;
}

/**
 * Seeds DataFrames from the example dataset, runs the user's function, and returns
 * the produced grid. Throws with the Python traceback's last line on failure.
 */
export async function runPandasAgainstSeed(
  solutionPath: string,
  schema: DbSchema,
  seed: readonly DbSeedTable[]
): Promise<PandasRunResult> {
  const plan = buildRunPlan(schema, seed);
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "lcex-pandas-"));
  const harnessPath = path.join(workDir, "lcex_pandas_harness.py");
  try {
    await fs.writeFile(harnessPath, buildHarness(solutionPath, plan), "utf8");
    const { stdout, stderr, exitCode } = await runSandboxed(
      `python3 -B ${quoteShellPath(harnessPath)}`,
      { cwd: workDir, timeout: RUN_TIMEOUT_MS, writePaths: [workDir] }
    );

    if (/No module named ['"]?pandas/.test(stderr)) {
      throw new PandasUnavailableError(
        "pandas is not installed for this python3. Install it with: python3 -m pip install pandas"
      );
    }
    if (/python3: command not found|No such file or directory/.test(stderr) && exitCode !== 0) {
      throw new PandasUnavailableError("python3 was not found on PATH.");
    }

    const marker = stdout.lastIndexOf(RESULT_SENTINEL);
    if (marker < 0) {
      throw new Error(pythonErrorSummary(stderr) || "the harness produced no result");
    }
    const lineEnd = stdout.indexOf("\n", marker);
    const json = stdout.slice(marker + RESULT_SENTINEL.length, lineEnd < 0 ? undefined : lineEnd);
    let parsed: DbGrid;
    try {
      parsed = JSON.parse(json) as DbGrid;
    } catch {
      throw new Error("could not parse the harness result");
    }
    const own = (stdout.slice(0, marker) + (lineEnd < 0 ? "" : stdout.slice(lineEnd + 1))).trim();
    return { grid: parsed, stdout: own };
  } finally {
    await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * Last meaningful line of a Python traceback. `RuntimeError: x` messages raised by
 * the harness read as plain guidance, so the prefix is stripped.
 */
export function pythonErrorSummary(stderr: string): string {
  const lines = stderr
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (/^(File|Traceback|\^|~|during handling|the above exception)/i.test(line)) continue;
    return line.replace(/^RuntimeError:\s*/, "");
  }
  return "";
}
